f = open('README.md', 'w')
f.write("# apkbuild-termux\n")
f.write("Build Android APK from your phone - No PC required!\n\n")
f.write("## Requirements\n")
f.write("- Termux\n- proot-distro Ubuntu\n- Android SDK 33\n- Java 17\n- Gradle 7.5\n\n")
f.write("## Installation\n")
f.write("bash setup.sh\n\n")
f.write("## Usage\n")
f.write("apkbuild new myapp\n")
f.write("apkbuild build myapp\n\n")
f.write("## Notes\n")
f.write("- First setup takes 30 minutes\n")
f.write("- APK saved to Downloads\n")
f.write("- No root required\n")
f.write("- Tested on ARM64\n")
f.write("## How it works\n")
f.write("This tool sets up Android environment inside Ubuntu on Termux.\n")
f.write("Uses Gradle 7.5 and Android SDK 33 to build real APK files.\n\n")
f.write("## Notes\n")
f.write("- First setup takes 30 minutes\n")
f.write("- Builds take 2 minutes\n")
f.write("- APK saved to Downloads\n")
f.write("- No root required\n")
f.write("- Tested on ARM64\n\n")
f.write("## Credits\n")
f.write("Built with love from a phone using Termux\n")
f.close()
print('done')
